-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stockdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stockdb` ;

-- -----------------------------------------------------
-- Schema stockdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockdb` DEFAULT CHARACTER SET utf8 ;
USE `stockdb` ;

-- -----------------------------------------------------
-- Table `stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock` ;

CREATE TABLE IF NOT EXISTS `stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(10) NOT NULL,
  `description` VARCHAR(10000) NOT NULL,
  `march_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `april_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `may_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `june_15_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `july_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `august_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `september_14_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `october_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `november_13_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `december_14_20_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `january_13_21_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `february_16_21_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `march_12_21_closing_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `average_volume_march_12` INT UNSIGNED NOT NULL,
  `market_cap_march_12_in_millions` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
--DROP USER stockuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'stockuser'@'localhost' IDENTIFIED BY 'stockuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'stockuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `stock`
-- -----------------------------------------------------
START TRANSACTION;
USE `stockdb`;
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (1, 'CTRM', 'Castor Maritime Inc., through its subsidiaries, engages in ocean transportation of dry bulk cargoes worldwide. It provides seaborne transportation services for dry bulk cargo, including iron ore, coal, grains, steel products, fertilizers, cement, bauxite, sugar, and scrap metals. The company operates three Panamax vessels with a carrying capacity of approximately 76,122 deadweight ton. Castor Maritime Inc. was founded in 2016 and is based in Limassol, Cyprus.', 0.66, 0.61, 0.66, 0.72, 0.25, 0.17, 0.15, 0.16, 0.13, 0.16, 0.37, 1.40, 1.02, 191813903, 518.68);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (2, 'SHIP', 'Seanergy Maritime Holdings Corp., an international shipping company, engages in the seaborne transportation of dry bulk commodities, primarily iron ore and coal worldwide. As of February 19, 2021, it operated a fleet of 11 Capesize vessels with a cargo-carrying capacity of approximately 1,926,117 deadweight ton and an average age of approximately 12 years. The company is headquartered in Athens, Greece.', 3.20, 2.24, 2.24, 2.72, 1.68, 1.27, 0.43, 0.50, 0.48, 0.49, 0.83, 2.26, 1.24, 20439475, 193.57);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (3, 'CCIV', 'Churchill Capital Corp IV does not have significant operations. It intends to effect a merger, capital stock exchange, asset acquisition, stock purchase, reorganization, or similar business combination with one or more businesses. The company was founded in 2020 and is based in New York, New York.', 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 9.70, 9.69, 9.98, 16.72, 52.70, 26.77, 48413075, 692700.00);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (4, 'BLNK', 'Blink Charging Co., through its subsidiaries, owns, operates, and provides electric vehicle (EV) charging equipment and networked EV charging services in the United States. The company offers residential and commercial EV charging equipment that enable EV drivers to recharge at various location types. It also provides Blink Network, a cloud-based system that operates, maintains, and tracks various Blink charging stations and associated charging data, as well as provides property owners, managers, and parking companies with cloud-based services that enable the remote monitoring and management of EV charging stations and payment processing; and provides EV drivers with station information, including station location, availability, and applicable fees. In addition, the company provides EV charging hardware, site recommendations, and maintenance services. It has strategic partnerships across transit/destination locations, including airports, auto dealers, healthcare/medicals, hotels, mixed-use, municipal locations, multifamily residential and condos, parks and recreation areas, parking lots, religious institutions, restaurants, retailers, schools and universities, stadiums, supermarkets, transportation hubs, and workplace locations. The company offers its services through field sales force and reseller partners, as well as sells home unit chargers through various internet channels. As of December 31, 2019, it had approximately 14,778 EV charging stations. The company was formerly known as Car Charging Group, Inc. and changed its name to Blink Charging Co. in August 2017. Blink Charging Co. was founded in 2009 and is headquartered in Miami Beach, Florida.', 1.91, 1.79, 1.73, 2.37, 5.99, 11.02, 6.70, 9.25, 9.70, 26.06, 50.81, 47.65, 39.31, 11965916, 163600.00);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (5, 'FCEL', 'FuelCell Energy, Inc., together with its subsidiaries, designs, manufactures, sells, installs, operates, and services stationary fuel cell power plants for distributed baseload power generation. The company offers SureSource product line based on carbonate fuel cell technology in various configurations, including on-site power, utility grid support, distributed hydrogen, and carbon utilization, as well as micro-grid and multi-megawatt applications; and SureSource Recovery power plants for natural gas pipeline applications. It also provides SureSource Capture system that separates and concentrates carbon dioxide from the flue gases of natural gas, biomass, or coal-fired power plants, as well as industrial facilities; and SOFC/SOEC and Energy Storage, a solution for energy storage using solid oxide technology. The company\'s SureSource power plants generate clean electricity, usable heat, water, and hydrogen. It serves various markets, such as utilities and independent power producers, industrial and process applications, education and health care, data centers and communication, wastewater treatment, government, morcrogrids, and commercial and hospitality. The company primarily operates in the United States, South Korea, England, Germany, and Switzerland. FuelCell Energy, Inc. was founded in 1969 and is headquartered in Danbury, Connecticut.', 1.15, 1.55, 1.88, 2.54, 2.81, 2.83, 2.26, 2.48, 2.85, 7.70, 19.14, 23.81, 18.16, 49183568, 585500.00);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (6, 'ADMP', 'Adamis Pharmaceuticals Corporation, a specialty biopharmaceutical company, develops and commercializes products in the therapeutic areas of allergy and respiratory disease in the United States. The company\'s specialty pharmaceutical product candidates comprise Symjepi (epinephrine) Injection pre-filled syringe (PFS) for use in the emergency treatment of acute allergic reactions, including anaphylaxis. It also offers dry powder inhaler products consisting of fluticasone (APC-4000) for the treatment of asthma; beclomethasone (APC-1000), a metered dose inhaler product for the asthma; Tadalafil (APC-8000) for the treatment of erectile dysfunction; and naloxone injection product candidates (APC-6000) for the treatment of opioid overdose. In addition, the company provides corticosteroids, hormone replacement therapies, hospital outsourcing products, injectables, urological preparations, topical compounds for pain, and men\'s and women\'s health products; and certain veterinary pharmaceutical products for animals. Adamis Pharmaceuticals Corporation is headquartered in San Diego, California.', 0.37, 0.36, 0.57, 0.64, 0.61, 1.02, 0.78, 0.94, 0.68, 0.52, 0.75, 1.57, 1.04, 19950135, 145.89);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (7, 'RIOT', 'Riot Blockchain, Inc., together with its subsidiaries, focuses on building, supporting, and operating Blockchain technologies ecosystem. It is involved in digital currency mining operation, which utilizes specialized computers that generate digital currency primarily bitcoin. The company also holds interests in various activities, including purchasing and selling digital currencies; provides accounting, audit, and verification services for blockchain based assets, such as cryptocurrencies; and develops TessPay, a payments ecosystem for component and sub-component supply chain settlement solution, as well as other blockchain solutions for telecommunications companies. As of December 31, 2019, approximately 7,400 of the miners were installed and operating. The company was formerly known as Bioptix, Inc. and changed its name to Riot Blockchain, Inc. in October 2017. Riot Blockchain, Inc. was founded in 2000 and is based in Castle Rock, Colorado.', 0.72, 1.01, 1.89, 2.31, 2.18, 3.61, 3.02, 3.37, 3.98, 9.14, 23.88, 59.50, 62.81, 34374331, 424200.00);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (8, 'CLBS', 'Caladrius Biosciences, Inc., a clinical-stage biopharmaceutical company, focuses on developing and commercializing cellular therapies to reverse disease and/or promote the regeneration of damaged tissue. Its product candidates include HONEDRA, a recipient of SAKIGAKE designation that is in Phase II clinical trial for the treatment of critical limb ischemia; OLOGO, a regenerative medicine advanced therapy for treating no-option refractory disabling angina; CLBS16 that is in Phase IIb clinical trial for the treatment of coronary microvascular dysfunction; and CLBS201, a CD34+ cell therapy for the treatment of pre-dialysis patients with chronic kidney disease. The company was formerly known as NeoStem, Inc. and changed its name to Caladrius Biosciences, Inc. in June 2015. Caladrius Biosciences, Inc. was incorporated in 1980 and is headquartered in Basking Ridge, New Jersey.', 1.83, 2.20, 2.16, 1.75, 2.16, 2.15, 1.99, 1.73, 1.52, 1.45, 1.55, 2.44, 2.17, 6218286, 129.12);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (9, 'CIDM', 'Cinedigm Corp., together with its subsidiaries, operates as distributor and aggregator of independent movie, television, and other short form content in the United States, Canada, and New Zealand. The company operates through two segments, Cinema Equipment Business and Content and Entertainment Business. It manages a library of distribution rights to various titles and episodes released across digital, physical, and home and mobile entertainment platforms, as well as services digital cinema assets on approximately 12,000 domestic and foreign movie screens. The company distributes its products for various brands, such as Hallmark, Televisa, ITV, Nelvana, ZDF, Shout! Factory, NFL, NHL and Scholastic, as well as international and domestic content creators, movie producers, television producers, and other short form digital content producers. It also collaborates with producers, various brands, and other content owners to market, source, curate, and distribute content to targeted audiences through existing and emerging digital home entertainment platforms, including Apple, Amazon Prime, Netflix, Hulu, Xbox, PlayStation, Sony, and cable/satellite video-on-demand; and distributes DVD and Blu-ray discs to wholesalers and retailers with sales coverage to approximately 60,000 brick and mortar storefronts, including Walmart, Target, Best Buy, and Amazon. In addition, the company operates various branded and curated over-the-top (OTT) entertainment channels, including Docurama, CONtv, and Dove Channel; and Matchpoint, a software-as-a-service platform to automate the distribution of streaming content and OTT channels. Cinedigm Corp. has a strategic alliance with Starrise Media Holdings Limited to release films in China theatrically and to digital platforms. The company was formerly known as Cinedigm Digital Cinema Corp. and changed its name to Cinedigm Corp. in September 2013. Cinedigm Corp. was founded in 2000 and is headquartered in New York, New York.', 0.35, 0.40, 0.55, 2.35, 1.92, 1.64, 0.67, 0.59, 0.60, 0.88, 0.86, 2.06, 1.25, 18292881, 207.44);
INSERT INTO `stock` (`id`, `ticker`, `description`, `march_13_20_closing_price`, `april_13_20_closing_price`, `may_13_20_closing_price`, `june_15_20_closing_price`, `july_13_20_closing_price`, `august_13_20_closing_price`, `september_14_20_closing_price`, `october_13_20_closing_price`, `november_13_20_closing_price`, `december_14_20_closing_price`, `january_13_21_closing_price`, `february_16_21_closing_price`, `march_12_21_closing_price`, `average_volume_march_12`, `market_cap_march_12_in_millions`) VALUES (10, 'CSCW', 'Color Star Technology Co., Ltd., through its subsidiaries, provides online and offline music education services in the United States and China. It also offers Color World, an online cultural entertainment platform that provides celebrity lectures, celebrity concert videos, celebrity peripheral products, and artist interactive communication. Color Star Technology Co., Ltd. has a strategic partnership with Yinmiao Culture Development Co., Ltd. to work together in the areas of piano competition, art festival coordination, and online and offline training, as well as artificial intelligence piano hardware research and development, production, and sales. The company was formerly known as Huitao Technology Co., Ltd., and changed its name to Color Star Technology Co., Ltd. in May 2020. Color Star Technology Co., Ltd. was founded in 2005 and is based in New York, New York.', 1.08, 0.41, 0.40, 0.69, 1.25, 1.05, 0.78, 0.63, 0.54, 0.51, 0.98, 1.33, 0.89, 9310315, 52.34);

COMMIT;
